version: "3.7"

services:
  # Elements node to run the daemon
  elementsd:
    container_name: "elementsd"
    image: ghcr.io/vulpemventures/elements:latest
    restart: unless-stopped
    command:
      - -rpcuser=${ELEMENTS_RPC_USER}
      - -rpcpassword=${ELEMENTS_RPC_PASS}
    ports:
      - 8333:8333 # PEER PORT
      - 8332:8332 # RPC PORT
      - 28332:28332 # block zmq
      - 28333:28333 # tx zmq
    volumes:
      - ./elementsd:/home/elements/.elements
  # TDEX daemon
  tdexd:
    container_name: "tdexd"
    image: ghcr.io/tdex-network/tdexd:latest
    restart: unless-stopped
    depends_on:
      - elementsd
    environment:
      - TDEX_LOG_LEVEL=5 # 5 for Debug. 4 for production
      - TDEX_CRAWL_INTERVAL=5000 # 5 seconds to poll blockchain
      - TDEX_ELEMENTS_RPC_ENDPOINT=http://${ELEMENTS_RPC_USER}:${ELEMENTS_RPC_PASS}@elementsd:8332
    ports:
      - "9945:9945"
      - "9000:9000"
    volumes:
      - ./tdexd:/.tdex-daemon
  # Pull prices from kraken and push to the daemon
  feederd:
    container_name: "feederd"
    image: ghcr.io/tdex-network/feederd:latest
    restart: unless-stopped
    depends_on:
      - tdexd
    volumes:
      - ./feederd:/data
