version: "3.7"

services:
  # Elements node
  liquid:
    container_name: liquid
    image: ghcr.io/vulpemventures/liquid:latest
    #restart: unless-stopped
    ports:
      - "7040:7040"
      - "7041:7041"
    volumes:
      - ${LIQUID_PATH}:/.elements
    command:
      - -datadir=/.elements
      - -validatepegin=0
      - -server=1
      - -listen=1
      - -txindex=1
      - -rpcuser=${LIQUID_RPC_USER}
      - -rpcpassword=${LIQUID_RPC_PASSWORD}
  # Blockstream Electrs explorer
  electrs:
    depends_on:
      - liquid
    container_name: electrs
    image: ghcr.io/vulpemventures/electrs-liquid:latest
    restart: unless-stopped
    ports:
      - "50001:50001"
      - "3000:3000"
    volumes:
      - ${LIQUID_PATH}:/.elements
    command:
      - -vvvv
      - --parent-network
      - liquid
      - --network
      - liquid
      - --daemon-dir
      - /.elements
      - --daemon-rpc-addr
      - liquid:7041
      - --cookie
      - ${LIQUID_RPC_USER}:${LIQUID_RPC_PASSWORD}
      - --http-addr
      - 0.0.0.0:3000
      - --electrum-rpc-addr
      - 0.0.0.0:50001
      - --cors
      - "*"
  tdexd:
    depends_on:
      - liquid
      - electrs
    container_name: "tdexd"
    image: ghcr.io/tdex-network/tdexd:latest
    restart: unless-stopped
    environment:
      - TDEX_EXPLORER_ENDPOINT=http://electrs:3000
      - TDEX_SSL_CERT=./cert.pem
      - TDEX_SSL_KEY=./key.pem
    ports:
      - "9945:9945"
      - "9000:9000"
    volumes:
      - ${TDEX_PATH}:/.tdex-daemon
      - ${SSL_CERT_PATH}:/cert.pem
      - ${SSL_KEY_PATH}:/key.pem
  feederd:
    depends_on:
      - tdexd
    container_name: "feederd"
    image: ghcr.io/tdex-network/feederd:latest
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}:/data/config.json
